server:
  port: 5011
  servlet:
    context-path: /auths
spring:
  profiles:
    active: home
  application:
    name: auth
  datasource:
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: ALWAYS
logging:
  level:
    root: error
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
