spring:
  datasource:
    url: jdbc:postgresql://${CLUSTER_URL}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        "[format_sql]": true
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}

logging:
  level:
    web: debug
    sql: error
    '[org.springframework.security]': error
    '[com.hangout.core]': trace
    # traceID and spanId are predefined MDC keys - we want the logs to include them
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

# All traces should be sent to latency analysis tool
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus, health
  # For Exemplars to work we need histogram buckets
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

hangout:
  jwt:
    secretKey: 
      access: ${ACCESS_TOKEN_SECRET}      
      refresh: ${REFRESH_TOKEN_SECRET}
  notification-service:
    url: ${NOTIFICATION_SERVICE}
  loki-server:
    url: ${LOKI_SERVER}