server:
  port: 5011
  servlet:
    context-path: /auths
spring:
  profiles:
    active: home
  application:
    name: auth
  datasource:
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: ALWAYS
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        
logging:
  level:
    web: error
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

hangout:
  kafka:
    topic:
      verification-mail: account-verification
      activation-mail: account-activation
