name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag opticsquid/hangout-auth-service:1.0.1
    - name: "Push to Dockerhub"
      run: docker push opticsquid/hangout-auth-service:1.0.1
    
